# Middlewares reutilizables (file provider).
# Referenciables desde labels como: security-headers@file
http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
